---
title: "Predict the President"
author: "Edward Baleni, BLNEDW003"
format: html
editor: visual
bibliography: references.bib
---

```{r}
require(dplyr)
require(stringr)
```


# Predict the President


```{r Data, echo=FALSE}
# Obtain dataset
dir       <- paste0(getwd(), "/Data/") 
ldf       <- list.files(path = dir, pattern = "*.txt")
data      <- data.frame() 

collectData <- function(fileName){
    dat     <- data.frame(readLines(fileName, warn = F))
    strings <- unlist(strsplit(fileName, "_"))
    string  <- gsub(".txt", "", strings[length(strings)])
    dat$President <- string
    # Remove first line as that's the date
    dat <- dat[-1,]
}

for (i in 1:length(ldf)){
  if (i == 1){
    data <- collectData(paste0(dir ,ldf[i]))
  }
  else {
    data <- rbind(data, collectData(paste0(dir ,ldf[i])))
  }
}
```



```{r Cleaning}
# remove cells that are just a space
# put everything in lower case
colnames(data) <- c("Text", "President")
data <- data %>% 
  select(President, Text) %>%
  filter(!(Text %in% ""))

data <- data.frame(lapply(data, str_to_lower))

############### May have to remove punctuation

# tokenize. Maay not have to tokenize
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```
